import = [
  "~/.dotfiles/alacritty/catppuccin-mocha.toml",
  "~/.dotfiles/alacritty/font.toml"
]

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Underline"
blinking = "On"

[window]
startup_mode = "Maximized"
