import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/font.toml",
]

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Underline"
blinking = "On"

[window]
startup_mode = "Maximized"
opacity=0.98
